### ISSUE TITLE
"callout warning" block doesn't play nice on mobile

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/dc_base_theme#11]
on desktop :+1: 

![screenshot - 191216](https://cloud.githubusercontent.com/assets/6025893/21326601/44663fc6-c623-11e6-9f61-953d7a424efd.png)

on android :-1: 

![screenshot_20161219-191950](https://cloud.githubusercontent.com/assets/6025893/21326618/5a781a82-c623-11e6-8c53-6f628a961114.png)

**Comment by symroe** [comment]
Thanks, I fixed this in DemocracyClub/WhoCanIVoteFor@f1cdc134254e241b67e32082368435f9ce586c4b in a hacky way, as the base theme needs some work anyway.
