### ISSUE TITLE
v0.3 theme still uses old v0.2 style logos in some assets

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/dc_base_theme#23]
e.g:
* https://github.com/DemocracyClub/dc_base_theme/blob/master/dc_theme/static/dc_theme/images/logo-large.png
* https://github.com/DemocracyClub/dc_base_theme/blob/master/dc_theme/static/dc_theme/images/logo.png

**Comment by chris48s** [comment]
Attempted to do something about this but the logos I found in in https://drive.google.com/drive/folders/0B6Qqb1WGnb7Wb01zNE9qWE04dmc don't quite match the ones we're using in 0.3 (the tick is differently positioned on the background). Need correct assets to sort this

**Comment by symroe** [comment]
Fairly sure #29 fixes this.
