### ISSUE TITLE
Upgrade to libsass 0.14.0

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_base_theme#30]
We need to test this against the different projects using it, but also look at python compatibility and general deployment issues that might exist. 

Refs https://github.com/DemocracyClub/UK-Polling-Stations/pull/1137#discussion_r174237770

**Comment by symroe** [comment]
I tried this and it seemed to work – needs more testing

**Comment by chris48s** [comment]
seems to work fine :+1:
