### ISSUE TITLE
Some form fields overflow parent divs

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_base_theme#31]
https://github.com/DemocracyClub/UK-Polling-Stations/pull/1137#issuecomment-372764590

**Comment by chris48s** [comment]
Having done a bit of testing, this seems to have worked pretty much everywhere I've tested it (I'll spare you the screenshots) except for on the front page, where it is still a problem:

![screenshot at 2018-03-16 10 38 14](https://user-images.githubusercontent.com/6025893/37517543-af7ebb72-2909-11e8-95e8-93f3dc2ec2d5.png)

**Comment by symroe** [comment]
Padding removed for tiny devices (under 330px):

![screenshot 2018-03-16 13 48 28](https://user-images.githubusercontent.com/242329/37524090-b9622f22-2920-11e8-9d97-0f8b71c802a0.png)
