### ISSUE TITLE
Generally better table styles

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_base_theme#32]
https://github.com/DemocracyClub/UK-Polling-Stations/pull/1137#issuecomment-372768433

**Comment by symroe** [comment]
![screenshot 2018-03-14 11 48 58](https://user-images.githubusercontent.com/242329/37400726-b7e2b67a-277d-11e8-816d-9ee985550777.png)

**Comment by chris48s** [comment]
this is loads better :+1:
