### ISSUE TITLE
Form Validation Issues

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_base_theme#33]
https://github.com/DemocracyClub/UK-Polling-Stations/pull/1137#issuecomment-372765566

**Comment by symroe** [comment]
Error styles updated to reflect [the GDS guidance](https://paper.dropbox.com/doc/Error-messages-fifEJpOYMGjRy0lHTmthb).

The error at the top of the postcode form is a little much for me, but I trust that the folk at GDS have tested and worked out the trade-offs. I know that in observation sessions I've been in, users tend not to notice error messages unless they are _very_ obvious, so I'm inclined to think that this is a good change. Happy to chat it over though.

![screenshot 2018-03-14 12 22 12](https://user-images.githubusercontent.com/242329/37402377-3aa9cd64-2783-11e8-9390-87b84784591a.png)

![screenshot 2018-03-14 12 14 55](https://user-images.githubusercontent.com/242329/37402380-3fdb0abe-2783-11e8-88f2-6b4c9f490f9a.png)

**Comment by chris48s** [comment]
I'd agree that the top error on postcode form could be toned down a bit, but if you do nothing additional I think this is an improvement over what we had before as it stands.

**Comment by chris48s** [comment]
:+1:
