### ISSUE TITLE
Better styling for API Documentation

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_base_theme#34]
https://github.com/DemocracyClub/UK-Polling-Stations/pull/1137#issuecomment-372767256

**Comment by symroe** [comment]
I've not recreated the response expand/collapse feature simply because I don't think it's a useful thing to have. For example, I didn't know it existed until I saw the gif on the PR.

We'll have to review this on the actual page (I've not been able to create them locally – I've just grabbed the HTML from the live site).

![screenshot 2018-03-14 14 42 39](https://user-images.githubusercontent.com/242329/37409324-f9c8df02-2795-11e8-9ea4-bdfa96dc4678.png)

**Comment by symroe** [comment]
Also, I can't decide between wrapping in the `<pre>` or scrolling. Screenshot above is scrolling.

Change to `white-space: pre-wrap;` on `code` to see what you'd rather.

**Comment by chris48s** [comment]
The screenshots in this post are from what I checked out yesterday.

1. Whatever you've done there seems to have done something odd with the body indenting and removed the syntax highlighting:

![screenshot at 2018-03-14 15 01 25](https://user-images.githubusercontent.com/6025893/37410638-f28a694c-2798-11e8-88d7-9ff4c6b3f6e7.png)

2. On the show/hide toggles, I do know what you mean for the small responses like the one you've picked above but on the more involved endpoints where there are >1 valid response patterns and the body + schema is long I think it is really useful for them to start collapsed. If you look at this:

![screenshot at 2018-03-14 15 01 45](https://user-images.githubusercontent.com/6025893/37410784-3e59d83a-2799-11e8-9bed-920bdf9aadee.png)

its much more clear that there are 3 OK responses that you need to handle (which is crucial). If you look at this:

![screenshot at 2018-03-14 15 02 22](https://user-images.githubusercontent.com/6025893/37410849-5dcbb062-2799-11e8-8ea5-705582ca8c75.png)

you've got a **lot** of scrolling to do before you hit the second 200 OK - its much more easily missed that this is the pattern.

Maybe @mrwilson would be a good person to give some feedback on this point given he has actually been through the process of starting with relatively little domain knowledge and reading these docs to extract the necessary information to build an application with them.

**Comment by chris48s** [comment]
(the changes on the _inline_ code blocks and HTTP method text are :+1: though)

**Comment by symroe** [comment]
On the highlighting, looks like the site pulls in `highlight.js`'s style sheet, and I'd not done that for the example page I was using as a test.

Pulling that in changes it to this:

![screenshot 2018-03-14 15 25 56](https://user-images.githubusercontent.com/242329/37412005-06eec146-279c-11e8-818d-6d317ee92730.png)

Also note that the indenting in the code block was caused by my copying and pasting the HTML out of the live site. I've manually fixed that in this screenshot.

**Comment by symroe** [comment]
Actually, it's possible that the code block hiding might work on the live version, as I've not pulled in all the assets. Let's wait until I've pushed and you can test locally before getting too far in to that.

**Comment by chris48s** [comment]
Sorry. Probs should have mentioned that all the code block highlighting/formatting is just handed over to [highlight.js](https://highlightjs.org/) to do its magic :sparkles:

**Comment by chris48s** [comment]
This is looking great now - loads clearer. The only small issue left is the links that have the 'edit' cursor - just need to apply `cursor-style: link` or whatever (may not be actual CSS :D ) to the `api-http-code` class and I'm really happy with this:

![gifrecord_2018-03-16_110801](https://user-images.githubusercontent.com/6025893/37517830-9a7b398e-290a-11e8-868b-35ed6caac991.gif)

**Comment by chris48s** [comment]
actually, maybe the right thing to do re: progressive enhancement is to add that style in the same place we add the event handler. That way if the page renders **without** JS it doesn't toggle and doesn't have a link cursor and if the page renders **with** JS then it does toggle and does have a link cursor
