### ISSUE TITLE
Nicer default 500 and 404 pages

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/dc_base_theme#36]
https://github.com/DemocracyClub/UK-Polling-Stations/pull/1137#issuecomment-372768433

**Comment by chris48s** [comment]
These are definitely more informative than "whoops" but the original issue, which is the the 500 page doesn't have a header/link back to the front page is still the same:

404 (with header):
![screenshot at 2018-03-16 10 54 40](https://user-images.githubusercontent.com/6025893/37517631-fda5a7de-2909-11e8-9109-299ff85dcb92.png)


500 (no header):
![screenshot at 2018-03-16 10 55 12](https://user-images.githubusercontent.com/6025893/37517635-048a5784-290a-11e8-98c0-b3934d70a5e4.png)
